name: Main Workflow

on: [push]

env:  
  NODE_VERSION: '12.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, lint, test and build
      run: |
        npm ci
        npm run lint        
        npm run test
        npm run build        
      env:
        CI: true
